
# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0" # https://github.com/mmistakes/minimal-mistakes

minimal_mistakes_skin: "dirt" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"


# Site Settings
title: Philipp Lang
subtitle: Data Science Consultant
name: Philipp Lang
email: your-email@domain.com
description: >
  This is my websites descriptions. it can be very long. And will spread several lines. So let's be a bit chatty.
logo: "/assets/images/Logo_small.png"
masthead_title: "My Custom Title"


# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/


header_pages:
  - about.md

show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

  # Social links in footer
  social_links:
    github: Mebbel


plugins:
 - jekyll-feed
 - jekyll-seo-tag



