
# Theme Settings
theme: minima


# Site Settings
title           : Philipp Lang - Data Science
description     : This is my first try.
locale          : "en-US"   


header_pages:
  - about.md

author:
  name: Philipp Lang
  email: "info@langphilipp.com"