
# Theme Settings
remote_theme: mmistakes/minimal-mistakes # https://github.com/mmistakes/minimal-mistakes #@4.24.0

minimal_mistakes_skin: "dirt" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
search: true


# Site Settings
title: Philipp Lang
subtitle: Data Science Consultant
name: Philipp Lang
email: your-email@domain.com
description: >
  This is my websites descriptions. it can be very long. And will spread several lines. So let's be a bit chatty.
logo: "/assets/images/Logo_small.png"
masthead_title: "My Custom Title"

# twitter_username:
github_username: Mebbel


# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/



